# Generated by Django 5.0.3 on 2024-05-29 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year_of_establishment', models.DateField()),
                ('is_international', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HotAirBalloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Montgolfier', 'Montgolfier'), ('Sky Lanterns', 'Sky Lanterns'), ('Tourism', 'Tourism'), ('Racing', 'Racing'), ('Observation', 'Observation'), ('Novelty', 'Novelty'), ('Advertising', 'Advertising')], max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birth_date', models.DateField(auto_now=True)),
                ('experience', models.IntegerField()),
                ('rank', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('takeoff_airport', models.CharField(max_length=50)),
                ('landing_airport', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flight_images/')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotAirBalloonApp.airline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hot_air_balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotAirBalloonApp.hotairballoon')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotAirBalloonApp.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='AirlinePilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotAirBalloonApp.airline')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotAirBalloonApp.pilot')),
            ],
        ),
    ]
