# Generated by Django 5.0.6 on 2024-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
