# Generated by Django 5.0.6 on 2024-07-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShopApp', '0002_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
