# Generated by Django 5.0.6 on 2024-05-30 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("link", models.URLField()),
                ("origin", models.CharField(max_length=50)),
                ("ceo", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WorkShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("year_started", models.IntegerField()),
                ("repairs_oldtimers", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sedan", "Sedan"),
                            ("hatchback", "Hatchback"),
                            ("cabriolet", "Cabriolet"),
                            ("wagon", "Wagon"),
                            ("coupe", "Coupe"),
                            ("oldtimer", "Old Timer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("max_speed", models.IntegerField()),
                ("paint", models.CharField(max_length=30)),
                ("isOldTimer", models.BooleanField()),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AutoRepairApp.manufacturer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("date", models.DateField(auto_now=True)),
                ("description", models.TextField(max_length=300)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="repairs/"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AutoRepairApp.car",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AutoRepairApp.workshop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManufacturerWorkshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AutoRepairApp.manufacturer",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AutoRepairApp.workshop",
                    ),
                ),
            ],
        ),
    ]
