# Generated by Django 5.0.6 on 2024-06-29 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('description', models.TextField(max_length=200)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('art_style', models.CharField(choices=[('impressionism', 'impressionism'), ('pop art', 'pop art'), ('graffiti', 'graffiti')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creation_date', models.DateField()),
                ('image', models.ImageField(upload_to='artpieces/')),
                ('art_exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGalleryApp.artexhibition')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGalleryApp.artist')),
            ],
        ),
    ]
